<?php

function mycomment_form_alter(&$form, &$form_state, $form_id) {
    //print '<pre>';
    print_r($form);
    //print '</pre>';

    // child_id = edit_subject
    // if($form_class == 'form_item_subject') {
    //     $form['copy']['#access'] = 0;
    //     $form['subject']['#access'] = 0;
    //     $form['subject']['#default_value'] = 'FeedBack';
    //     $form['copy']['#default_value'] = 1 ;
    // }


}
